### ISSUE TITLE
Question/Help needed: Basic setup 

### ISSUE THREAD

**Issue by flowck** [uditalias/injex#16]
Hi @uditalias,
First of all, great work, I really like the idea of auto-scanning all the classes/modules annotated with `@define`.

I've created this small demo https://github.com/flowck/injex-demo where I attempt to implement `injex/node`, but I can't make it work, and the `run()` method from the bootstrap class doesn't quite run. I probably made a basic mistake somewhere but I can't quite figure it out.

When I try to run the application after being compiled, I get this error: 

![Screenshot 2021-03-15 at 21 55 22](https://user-images.githubusercontent.com/1679333/111226512-28923500-85d9-11eb-99c7-d35032abeebd.png)

Sorry for this issue.

Kind regards,
Firmino.

**Comment by uditalias** [comment]
Hey @flowck 
Thank you! I'm happy to hear you find Injex helpful
Let me take a look at your code and I'll get back to you

**Comment by uditalias** [comment]
Hello gain @flowck :)

I found and fixed the issues, you can check out my comments in the [code here](https://github.com/uditalias/injex-demo/commit/7ba24bd6df161d361896bc23761ca966a4b353f0)

It's a fork version of your demo with explanations of what went wrong.

Notice that your code revealed a bug I had in the `@injex/core` package (Thank you 🙏) and I fixed it on `3.0.0-alpha.1`

Let me know if you have any other questions and everything is working now.

**Comment by flowck** [comment]
Hi @uditalias,

Many thanks, it works. 🚀🚀🚀

I'll be exploring a lot more, and hopefully write a couple of articles about it. It's a good solution because it doesn't require a crazy setup. 

Thanks!!!
